const NEURAL_EARTH_ROOT = require('node:path').resolve(__dirname, '../..');
process.chdir(NEURAL_EARTH_ROOT);
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const {sampleHeight, distanceLabel} = require(NEURAL_EARTH_ROOT + '/terrain_map_tools.js');
const {chromium} = require(process.env.PLAYWRIGHT_PATH || 'E:/TerrainDiffusionRuntime/ui-test/node_modules/playwright');

// Bilinear sampling respects pixel centres, halo, and negative map coordinates.
const grid = new Float32Array(16);
grid[5] = -100; grid[6] = 100; grid[9] = 300; grid[10] = 500;
const tile = {heights:grid, heightOptions:{width:4,halo:1}, b:[-20,-20,0,0]};
assert.equal(sampleHeight(tile,{x:-15,y:-15}),-100);
assert.equal(sampleHeight(tile,{x:-10,y:-10}),200);
assert.equal(sampleHeight(tile,{x:-5,y:-5}),500);
assert.equal(sampleHeight({}, {x:0,y:0}),null);
assert.equal(distanceLabel(1500),'1.50 km');

(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-gpu']});
  try {
    const page = await browser.newPage({viewport:{width:1280,height:900}});
    const errors = [], requests = [];let pauseWorld=false,releaseWorld,snrHeightRequests=0,computing=0;
    page.on('pageerror',e=>errors.push(e.message));
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAEklEQVR4nGM0LJrHwMDAxAAGAA7JAUW48M0QAAAAAElFTkSuQmCC','base64');
    const physical = new Float32Array(304*304+5*33*33); physical.fill(-125.5,0,304*304);
    const gpuStub = `window.createTerrainRenderer=async()=>{const tiles=new Set();return{available:true,uploadTile(k){tiles.add(k)},hasTile(k){return tiles.has(k)},deleteTile(k){tiles.delete(k)},clear(){tiles.clear()},draw(rects){this.lastDrawnRects=rects.filter(r=>tiles.has(r.key));return true},getStats(){return{status:'webgpu'}}}}`;
    await page.route('https://map-tools.test/**',async route => {
      const u = new URL(route.request().url()); requests.push(u.pathname);
      if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('index.html','utf8')});
      if(u.pathname==='/terrain_renderer.js')return route.fulfill({contentType:'application/javascript',body:gpuStub});
      if(u.pathname==='/terrain_styles.js')return route.fulfill({contentType:'application/javascript',body:'window.TerrainStyles='+fs.readFileSync('terrain_styles.json','utf8')+';\n'+fs.readFileSync('terrain_style_rendering.js','utf8')});
      if(['/terrain_lighting.js','/terrain_globe.js','/terrain_lod.js','/terrain_generation_controls.js','/terrain_map_tools.js','/terrain_toolbar.js'].includes(u.pathname))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(u.pathname.slice(1),'utf8')});
      if(u.pathname==='/api/generation/run'){const data=route.request().postDataJSON();return route.fulfill({json:{world_profile:data.profile,generation_settings:data.settings}});}
      if(u.pathname==='/api/world'){if(pauseWorld)await new Promise(resolve=>releaseWorld=resolve);return route.fulfill({json:{version:'natural-v1',cache_profile:'mock',world_profile:u.searchParams.get('world_profile'),generation_profile:u.searchParams.get('world_profile'),seed:u.searchParams.get('seed'),world_bounds:[-500000,-250000,500000,250000],overview_bounds:[-500000,-250000,500000,250000],overview:'/overview.png',gpu:'Mock GPU',generation_schema:{properties:JSON.parse(fs.readFileSync('native/orogen/climate-parameters.json','utf8'))}}});}
      if(u.pathname==='/api/status')return route.fulfill({json:{scheduler:{queued:0,computing,encoding:0}}});
      if(u.pathname==='/api/view')return route.fulfill({json:{accepted:true}});
      if(u.pathname.startsWith('/height/')){
        if(u.searchParams.get('mode')?.startsWith('snr-'))snrHeightRequests++;
        const source=u.searchParams.get('source_lod'),lod=Number(u.pathname.split('/')[4]),width=source?256/2**(3-lod)+48:304;
        const values=new Float32Array(width*width+(u.searchParams.has('climate')?5*33*33:0));values.fill(-125.5,0,width*width);
        return route.fulfill({contentType:'application/octet-stream',body:Buffer.from(values.buffer),headers:{'X-Terrain-Width':String(width),'X-Terrain-Halo':'24','X-Terrain-Climate-Width':u.searchParams.has('climate')?'33':'0','X-Terrain-Climate-Height':u.searchParams.has('climate')?'33':'0','X-Terrain-Stage':source?'latent':'decoder','X-Terrain-Source-LOD':source||String(lod),'X-Terrain-Source-Resolution':source?'240':'30'}});
      }
      return route.fulfill({contentType:'image/png',body:png,headers:u.pathname.startsWith('/tiles/')?{'X-Terrain-Source-LOD':u.searchParams.get('source_lod')||u.pathname.split('/')[4],'X-Terrain-Stage':u.searchParams.has('source_lod')?'latent':'decoder'}:{}});
    });
    await page.goto('https://map-tools.test/?seed=42&profile=natural&coarse_gpu=0&coarse_prepare=0');
    const settle = () => page.waitForFunction(()=>terrainDebug.snapshot().visible.ready>0 && terrainDebug.snapshot().visible.pending===0);
    await settle();
    assert.equal(await page.locator('#legend').isVisible(),false);
    assert.equal(await page.locator('#lodIndicator').textContent(),'LOD '+(await page.evaluate(()=>terrainDebug.snapshot().camera.lod)));
    await page.waitForFunction(()=>document.getElementById('loadingIndicator').hidden);
    assert.equal(await page.locator('#worldPanel').count(),0);
    for(const id of ['seed','random','apply'])assert.equal(await page.locator('#'+id).isVisible(),true);
    const viewBeforeRendering=await page.locator('#viewport').boundingBox();
    assert.equal(await page.locator('#idleRefinement').count(),0);
    assert.equal(await page.locator('#refinementDepth').inputValue(),'0');
    assert.equal(await page.locator('#refinementDepth').getAttribute('min'),'0');
    await page.locator('#renderPanel > summary').click();
    assert.deepEqual(await page.locator('#viewport').boundingBox(),viewBeforeRendering);
    assert.equal(await page.locator('#renderSea').isChecked(),false);
    assert.equal(await page.locator('#seaMaxLod').inputValue(),'9');
    assert.equal(await page.locator('#cacheLodGap').inputValue(),'3');
    assert.equal(await page.locator('#cacheBudgetGiB').inputValue(),'2');
    assert.equal(await page.evaluate(()=>terrainDebug.snapshot().cache.budget),2*1024**3);
    await page.locator('#cacheBudgetGiB').fill('0.375');
    await page.locator('#cacheBudgetGiB').dispatchEvent('change');
    assert.equal(await page.evaluate(()=>terrainDebug.snapshot().cache.budget),.375*1024**3);
    assert.equal(await page.evaluate(()=>new URLSearchParams(location.search).get('cache_gib')),'0.375');
    await page.locator('#cacheBudgetGiB').fill('');
    await page.locator('#cacheBudgetGiB').dispatchEvent('change');
    assert.equal(await page.locator('#cacheBudgetGiB').inputValue(),'0.375');
    await page.reload();await settle();
    assert.equal(await page.locator('#cacheBudgetGiB').inputValue(),'0.375');
    assert.equal(await page.evaluate(()=>terrainDebug.snapshot().cache.budget),.375*1024**3);
    await page.locator('#renderPanel > summary').click();
    for(const id of ['renderSea','seaMaxLod','cacheLodGap','cacheBudgetGiB','forcedLod','gpuRender','refinementDepth','prefetch']){
      assert.equal(await page.locator('#'+id).isVisible(),true);
      assert.equal(await page.locator('#'+id).evaluate(el=>!!el.closest('#renderPanel')),true);
    }
    await page.screenshot({path:path.join(os.tmpdir(),'infinite-map-rendering-desktop.png')});
    await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);
    assert.ok(await page.locator('#renderPanel .toolPanel').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
    await page.screenshot({path:path.join(os.tmpdir(),'infinite-map-rendering-mobile.png')});
    await page.setViewportSize({width:1280,height:900});
    await page.locator('#renderPanel .panelClose').click();
    const initialWorldRequests=requests.filter(p=>p==='/api/world').length;
    await page.locator('#random').click();
    await page.waitForFunction(()=>terrainDebug.snapshot().world!=='42');await settle();
    assert.notEqual(await page.locator('#seed').inputValue(),'42');
    assert.equal(requests.filter(p=>p==='/api/world').length,initialWorldRequests+1,'Random generates the complete world');
    await page.locator('#seed').fill('42');
    computing=1;
    await page.waitForFunction(()=>!document.getElementById('loadingIndicator').hidden);
    assert.equal(await page.locator('#loadingIndicator').isVisible(),true);
    computing=0;
    await page.waitForFunction(()=>document.getElementById('loadingIndicator').hidden);
    assert.equal(await page.locator('#loadingIndicator').isVisible(),false);
    pauseWorld=true;
    await page.locator('#apply').click();
    await page.waitForFunction(()=>document.getElementById('loadingIndicator').textContent.includes('Opening world')&&!document.getElementById('loadingIndicator').hidden);
    assert.equal(await page.locator('#viewport').getAttribute('aria-busy'),'true');
    pauseWorld=false;releaseWorld();await settle();await page.waitForFunction(()=>document.getElementById('loadingIndicator').hidden);
    await page.keyboard.press('Escape');
    const mapBeforeSettings=await page.locator('#viewport').boundingBox();
    await page.locator('#generationPanel > summary').click();
    assert.equal(await page.locator('#generatorType').inputValue(),'natural');
    await page.locator('#generatorType').selectOption('orogen');
    assert.equal(await page.locator('#orogenParameters').isVisible(),true);
    assert.equal(await page.locator('#proceduralParameters').isVisible(),false);
    assert.equal(await page.locator('#noisePanel #snr0').count(),1,'common relief SNR lives in its dedicated panel');
    await page.locator('#generatorType').selectOption('custom');
    assert.equal(await page.locator('#orogenParameters').isVisible(),true);
    assert.equal(await page.locator('#frequency0').isVisible(),false);
    assert.equal(await page.locator('#frequency1').isVisible(),false);
    await page.locator('#generatorType').selectOption('natural');
    assert.deepEqual(await page.locator('#viewport').boundingBox(),mapBeforeSettings,'settings overlay must preserve map geometry');
    const worldRequests=requests.filter(path=>path==='/api/world').length;
    await page.locator('#tabClimate').click();
    assert.equal(await page.locator('#climateSource').inputValue(),'orogen');
    await page.locator('#orogenClimateSearch').fill('snow');
    await page.locator('#orogen_biome_tropical_snowSlider').focus();await page.keyboard.press('ArrowLeft');
    assert.equal(await page.evaluate(()=>generationControls.read().orogen_biome_tropical_snow),5.45);
    await page.locator('#orogen_biome_tropical_snow').fill('4.125');
    await page.locator('#orogenClimateSearch').fill('Af color');
    await page.locator('#orogen_biome_color_af').fill('#448822');
    const draft=await page.evaluate(()=>generationControls.read());
    assert.equal(draft.orogen_biome_tropical_snow,4.125,'exact entry must retain precision beyond slider steps');
    assert.deepEqual(draft.orogen_biome_color_af,[68/255,136/255,34/255]);
    for(const key of Object.keys(JSON.parse(fs.readFileSync('native/orogen/climate-parameters.json','utf8'))))assert.ok(key in draft,key+' must be editable');
    assert.equal(requests.filter(path=>path==='/api/world').length,worldRequests,'draft changes must not generate a world');
    await page.locator('#resetGeneration').click();
    await page.waitForFunction(()=>document.getElementById('generationDraftStatus').textContent==='Tous les paramètres de génération sont réinitialisés.');
    const reset=await page.evaluate(()=>generationControls.read());
    const climateDefaults=JSON.parse(fs.readFileSync('native/orogen/climate-parameters.json','utf8'));
    for(const [key,spec] of Object.entries(climateDefaults))assert.deepEqual(reset[key],spec.default,key+' resets with property-only schema');
    await page.locator('#orogenClimateSearch').fill('');
    await page.locator('#renderPanel > summary').click();await page.locator('#tabSnr').click();
    await page.locator('#generationPreset').selectOption('mountains');
    assert.deepEqual(await page.evaluate(()=>generationControls.read().snr_altitude_gain),[4,1,1,1,1]);
    await page.locator('#generationPreset').selectOption('glacial');
    assert.deepEqual(await page.evaluate(()=>generationControls.read().snr_driver_gain),[3,1,1,1,1]);
    assert.deepEqual(await page.evaluate(()=>generationControls.read().snr_driver_range),[5,-10]);
    await page.locator('#generationPreset').selectOption('current');
    await page.locator('#renderPanel > summary').click();
    await page.locator('#plus').click(); await page.locator('#plus').click(); await settle();
    const box = await page.locator('#viewport').boundingBox(), x=box.x+box.width/2, y=box.y+box.height/2;
    await page.mouse.move(x,y);
    await page.waitForFunction(()=>document.getElementById('cursorAltitude').textContent.includes('-125.5 m'));
    assert.match(await page.locator('#visibleExtent').textContent(),/width × height/);
    assert.match(await page.locator('#visibleExtent').textContent(),/km · \d+ × \d+ px/);
    const before = await page.evaluate(()=>terrainDebug.snapshot().camera);
    await page.locator('#measureDistance').click();
    await page.mouse.move(x,y); await page.mouse.down(); await page.mouse.move(x+120,y+90,{steps:4});
    await page.mouse.up();
    await page.waitForFunction(()=>document.getElementById('measureDistance').getAttribute('aria-pressed')==='false');
    assert.equal(await page.locator('#measuredDistance').textContent(),`Distance on map: ${distanceLabel(150*before.mpp)}`);
    const after = await page.evaluate(()=>terrainDebug.snapshot().camera);
    assert.equal(after.cx,before.cx); assert.equal(after.cy,before.cy);
    await page.mouse.move(x,y); await page.mouse.down(); await page.mouse.move(x+20,y); await page.mouse.up();
    assert.notEqual((await page.evaluate(()=>terrainDebug.snapshot().camera)).cx,before.cx,'next drag pans normally');
    await page.locator('#measureDistance').click(); await page.mouse.move(x,y); await page.mouse.down();
    await page.mouse.move(x+30,y+30); await page.keyboard.press('Escape'); await page.mouse.up();
    await page.waitForFunction(()=>document.getElementById('measuredDistance').textContent==='Distance: —');
    assert.equal(await page.locator('#measureDistance').getAttribute('aria-pressed'),'false');
    await page.locator('#renderPanel').evaluate(el=>el.open=true);await page.locator('#tabRendering').click();await page.locator('#gpuRender').uncheck(); await settle();
    await page.mouse.move(x,y);
    await page.waitForFunction(()=>document.getElementById('cursorAltitude').textContent.includes('-125.5 m'));
    assert.ok(requests.some(p=>p.startsWith('/height/')),'PNG fallback retrieves physical heights');
    await page.mouse.move(2,2);
    await page.waitForFunction(()=>document.getElementById('cursorAltitude').textContent==='Cursor elevation: —');
    await page.locator('#measureDistance').click(); await page.mouse.move(x,y); await page.mouse.down(); await page.mouse.move(x+120,y+90); await page.mouse.up();
    const screenshot = path.join(os.tmpdir(),'infinite-map-tools.png');
    await page.screenshot({path:screenshot});
    await page.locator('#mapMode').selectOption('snr-elevation',{force:true});await settle();
    assert.equal(await page.evaluate(()=>terrainDebug.snapshot().backend),'png');
    await page.mouse.move(x,y);await page.waitForTimeout(150);
    assert.equal(snrHeightRequests,0,'SNR display and hover must not request NN terrain');
    assert.equal(await page.locator('#snrLegend').isVisible(),true);
    await page.locator('#renderPanel').evaluate(el=>el.open=true);await page.locator('#mapMode').selectOption('snr-temperature',{force:true});await settle();
    assert.match(await page.locator('#snrScaleLabel').textContent(),/Temperature/);
    await page.locator('#renderPanel').evaluate(el=>el.open=true);await page.locator('#layerPanel > summary').click();await page.locator('[data-mode=relief]').click();await settle();
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(100);
    assert.ok(await page.locator('#hud').evaluate(el=>el.getBoundingClientRect().right <= innerWidth));
    assert.ok(await page.locator('#lodIndicator').isVisible());
    assert.ok(await page.locator('#controls').evaluate(el=>el.scrollWidth<=innerWidth),'toolbar must not overflow on mobile');
    assert.deepEqual(errors,[]);
    console.log('Map tools passed: bilinear altitude, GPU/PNG, extent, distance, pan restoration, Escape, mobile HUD.');
    console.log(screenshot);
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
