const NEURAL_EARTH_ROOT = require('node:path').resolve(__dirname, '../..');
process.chdir(NEURAL_EARTH_ROOT);
// Browser regression using the local viewer, synthetic NN tiles and real WebGL.
const {chromium}=require(NEURAL_EARTH_ROOT + '/webgpu/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1100,height:760}}),errors=[],subscriptions=[],tileRequests=[],preparations=[];
  await page.addInitScript(()=>Object.defineProperty(navigator,'gpu',{value:undefined}));
  page.on('pageerror',e=>errors.push(e.message));
  const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#ff0044';g.fillRect(0,0,256,256);return c.toDataURL().split(',')[1]});
  const overviewPng=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#0044ff';g.fillRect(0,0,256,256);return c.toDataURL().split(',')[1]});
  await page.route('**/api/world?**',route=>route.fulfill({json:{seed:'42',world_profile:'natural',generation_profile:'natural',gpu:'test',version:'test-v1',cache_profile:'test',world_topology:'sphere',world_diameter_km:12732.4,world_bounds:[-20e6,-10e6,20e6,10e6],overview_bounds:[-20e6,-10e6,20e6,10e6],overview:'/overview/test.png'}}));
  await page.route('**/api/view',route=>{const body=route.request().postDataJSON();subscriptions.push({url:route.request().url(),body});return route.fulfill({json:{accepted:true,epoch:body.epoch}})});
  await page.route('**/api/status',route=>route.fulfill({json:{scheduler:{queued:0,computing:0,encoding:0}}}));
  await page.route('**/overview/test.png?**',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from(overviewPng,'base64')}));
  await page.route('**/tiles/test-v1/**',route=>{tileRequests.push(route.request().url());return route.fulfill({status:200,contentType:'image/png',headers:{'X-Terrain-Stage':'decoder','X-Terrain-Elevation-Min':'10','X-Terrain-Elevation-Max':'100'},body:Buffer.from(png,'base64')})});
  await page.route('**/api/view/release',route=>route.fulfill({json:{released:true}}));
  await page.route('**/api/coarse/prepare',route=>{preparations.push(route.request().postDataJSON());return route.fulfill({json:{state:'idle'}})});
  await page.goto('http://127.0.0.1:8765/?seed=42&profile=natural&view=globe&coarse_prepare=1&lighting='+encodeURIComponent(JSON.stringify({global:{strength:0}})));
  await page.waitForFunction(()=>window.terrainDebug?.snapshot().globe?.detailReady);
  assert.equal(await page.locator('#controls > .sceneViews > button').count(),2);
  assert.equal(await page.locator('#viewPanel').count(),0);
  assert.deepEqual(preparations,[],'old links must not start global computation');
  assert.equal(await page.locator('#prepareEntireWorld').isChecked(),false);
  await page.locator('#prepareEntireWorld').evaluate(e=>{e.checked=true;e.dispatchEvent(new Event('change'))});
  await page.waitForFunction(()=>new URLSearchParams(location.search).get('prepare_world')==='1');
  await page.waitForTimeout(100);
  assert(preparations.some(p=>p.full_world),'explicit opt-in starts global work');
  await page.locator('#prepareEntireWorld').evaluate(e=>{e.checked=false;e.dispatchEvent(new Event('change'))});
  await page.waitForTimeout(100);
  assert(preparations.some(p=>p.action==='stop'),'opt-out stops global work');
  await page.locator('#plus').click({clickCount:10,delay:20});
  await page.waitForFunction(()=>window.terrainDebug.snapshot().camera.lod<=2);
  await page.waitForFunction(()=>{const s=window.terrainDebug.snapshot();return s.visible.pending===0&&s.rendered.sources.includes('decoder')});
  await page.screenshot({path:'tmp/globe-browser.png'});
  const first=await page.evaluate(()=>window.terrainDebug.snapshot());
  const pixel=await page.locator('#globeMap').evaluate(c=>{globe.draw(c.clientWidth,c.clientHeight);const gl=c.getContext('webgl'),p=new Uint8Array(4);gl.readPixels(c.width/2,c.height/2,1,1,gl.RGBA,gl.UNSIGNED_BYTE,p);return [...p]});
  assert(pixel[0]>pixel[1]*2&&pixel[0]>pixel[2]*2,'learned tile replaces the original global relief');
  assert(first.globe.detailReady&&first.rendered.patches>0);assert(tileRequests.some(url=>/\/42\/[0123]\//.test(url)));
  assert(subscriptions.some(s=>s.body.tiles.length>0));
  await page.locator('#refinementDepth').evaluate(e=>{e.value='1';e.dispatchEvent(new Event('change'))});
  await page.waitForFunction(()=>{const s=window.terrainDebug.snapshot();return s.rendered.lods.every(l=>l===s.camera.lod-1)&&s.rendered.patches>0});
  await page.locator('#nnEngine').evaluate(e=>{e.value='reference';e.dispatchEvent(new Event('change'))});
  await page.waitForFunction(()=>{const s=window.terrainDebug.snapshot();return s.nnEngine==='reference'&&s.globe.detailReady&&s.cache.keys.some(k=>k.startsWith('reference/'))});
  assert(tileRequests.some(url=>url.includes('/reference/tiles/')));
  assert(subscriptions.some(s=>s.url.includes('/reference/api/view')&&s.body.tiles.length>0));
  const reference=await page.evaluate(()=>window.terrainDebug.snapshot());
  assert(reference.globe.altitude===first.globe.altitude,'engine switch preserves globe zoom');
  await page.waitForFunction(()=>window.terrainDebug.snapshot().visible.pending===0&&refinementProgress()?.complete);
  const beforeSwitch=tileRequests.length;
  await page.evaluate(()=>{window.sharedPngTiles=new Map(tiles);mapCamera=null});
  await page.locator('#mapView').click();await page.waitForFunction(()=>{const s=window.terrainDebug.snapshot();return s.view==='map'&&s.visible.pending===0&&s.rendered.patches>0});
  assert(await page.evaluate(()=>[...sharedPngTiles].every(([key,tile])=>tiles.get(key)===tile)),'PNG render objects survive switching to map');
  await page.locator('#globeView').click();await page.waitForFunction(()=>window.terrainDebug.snapshot().globe.detailReady&&window.terrainDebug.snapshot().visible.pending===0);
  await page.waitForTimeout(150);
  assert.equal(tileRequests.length,beforeSwitch,'same region reuses PNG tiles without downloading again');
  const orientation=await page.evaluate(()=>{
   globe.fit();syncGlobeCamera();
   const quad=document.createElement('canvas');quad.width=quad.height=256;const q=quad.getContext('2d');
   for(const [x,y,color]of [[0,0,'#ff0000'],[128,0,'#00ff00'],[0,128,'#0000ff'],[128,128,'#ffff00']]){q.fillStyle=color;q.fillRect(x,y,128,128)}
   rect(quad,worldBounds());const points=[[.3,.3],[.7,.3],[.3,.7],[.7,.7]],map=points.map(([x,y])=>[...ctx.getImageData(Math.floor(canvas.width*x),Math.floor(canvas.height*y),1,1).data]);
   const readGlobe=()=>{globe.draw(W,H);const c=$('globeMap'),gl=c.getContext('webgl');return points.map(([x,y])=>{const pixel=new Uint8Array(4);gl.readPixels(Math.floor(c.width*x),c.height-1-Math.floor(c.height*y),1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);return [...pixel]})};
   globe.setTiles([],null,null);globe.setImage(quad);const atlas=readGlobe();
   const black=document.createElement('canvas');black.width=black.height=1;globe.setImage(black);
   globe.setTiles([{tile:{key:'orientation',image:quad},bounds:worldBounds(),uv:[0,0,1,1]}],globe.camera(W,H,worldBounds()),worldBounds());
   return {map,atlas,detail:readGlobe()};
  });
  assert.deepEqual(orientation.atlas,orientation.map,'global overview matches map orientation');
  assert.deepEqual(orientation.detail,orientation.map,'PNG detail matches map orientation');
  const webgl=await page.locator('#globeMap').evaluate(c=>c.getContext('webgl').getError());assert.equal(webgl,0);
  assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'OK',tileRequests:tileRequests.length,globe:first.globe,lods:first.rendered.lods,reference:reference.nnEngine}));
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
