const {loadPlaywright, browserExecutable, runtimePath} = require('../platform.cjs');
const NEURAL_EARTH_ROOT = require('node:path').resolve(__dirname, '../..');
process.chdir(NEURAL_EARTH_ROOT);
const {chromium}=loadPlaywright();
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:browserExecutable(),headless:true});try{
 const page=await browser.newPage({viewport:{width:1000,height:700}}),errors=[],urls=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>urls.push(r.url()));
 await page.goto('http://127.0.0.1:8765/?seed=42&profile=natural&mode=relief');
 await page.waitForFunction(()=>document.getElementById('viewport').dataset.loaded>0,{},{timeout:120000});
 assert(!await page.locator('header').innerText().then(s=>s.includes('Île')));
 const meta=await(await page.request.get('http://127.0.0.1:8765/api/world?seed=42&world_profile=natural')).json();
 assert.match(meta.version,/^natural-/);assert.deepEqual(meta.initial_bounds,[-107520,76800,15360,138240]);
 assert(urls.some(u=>u.includes(`/tiles/${meta.version}/`)||u.includes(`/height/${meta.version}/`)));
 const cameraEpoch=await page.evaluate(()=>window.terrainDebug.snapshot().cameraEpoch);
 await page.locator('#initialView').click();
 await page.locator('#native').click();
 await page.waitForFunction(previous=>{const s=window.terrainDebug.snapshot();return s.cameraEpoch>previous&&s.camera.lod===0&&s.visible.lod===0&&s.visible.wanted>0&&s.visible.pending===0},cameraEpoch,{timeout:120000});
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 assert((await page.locator('header').innerText()).includes('Monde procédural'));
 await page.screenshot({path:runtimePath('realtime-qa/natural-viewer.png')});
 assert.deepEqual(errors,[]);console.log('PASS: original region, natural tiles, native30m, no JS errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
